### ISSUE TITLE
[Bug]: There are a lot of broken texture texture

### ISSUE THREAD

**Issue by tbvns** [DimensionalDevelopment/DimDoors#328]
### What happened?

When you launch fabric with this mod, you get a lot of warn.
They look like this:
`17:59:29.752
Exception loading blockstate definition: 'dimdoors:blockstates/amalgam_trapdoor.json' missing model for variant: 'dimdoors:amalgam_trapdoor#facing=east,half=bottom,open=true,powered=false,waterlogged=false'
17:59:29.752
Exception loading blockstate definition: 'dimdoors:blockstates/amalgam_trapdoor.json' missing model for variant: 'dimdoors:amalgam_trapdoor#facing=west,half=bottom,open=false,powered=true,waterlogged=false'
17:59:29.752
Exception loading blockstate definition: 'dimdoors:blockstates/amalgam_trapdoor.json' missing model for variant: 'dimdoors:amalgam_trapdoor#facing=west,half=bottom,open=true,powered=true,waterlogged=false'
17:59:29.752
Exception loading blockstate definition: 'dimdoors:blockstates/amalgam_trapdoor.json' missing model for variant: 'dimdoors:amalgam_trapdoor#facing=south,half=top,open=true,powered=true,waterlogged=true'
17:59:29.752
Exception loading blockstate definition: 'dimdoors:blockstates/amalgam_trapdoor.json' missing model for variant: 'dimdoors:amalgam_trapdoor#facing=south,half=bottom,open=true,powered=false,waterlogged=false'
17:59:29.752
Exception loading blockstate definition: 'dimdoors:blockstates/amalgam_trapdoor.json' missing model for variant: 'dimdoors:amalgam_trapdoor#facing=south,half=bottom,open=false,powered=false,waterlogged=true'
17:59:29.752
Exception loading blockstate definition: 'dimdoors:blockstates/amalgam_trapdoor.json' missing model for variant: 'dimdoors:amalgam_trapdoor#facing=north,half=top,open=false,powered=true,waterlogged=true'`

It really slows the loading of minecraft.
I'm using fabric 0.14.12 on 1.19.2.

### Mod Version

5.0.1

### What versions of Minecraft does this issue happen on?

1.19.3

### Log

```shell
There are 26,158 warn. Do you really want them here ?
```

**Comment by BoogieMonster1O1** [comment]
Fixed in 5.1.0

**Comment by KevlarBandit** [comment]
The new update 5.0.2 Doesn't fix this issue:
`[01:34:30] [Worker-Main-13/WARN]: Unable to load model: 'dimdoors:stone_player#inventory' referenced from: dimdoors:stone_player#inventory: java.io.FileNotFoundException: dimdoors:models/item/stone_player.json
 [01:34:30] [Worker-Main-13/WARN]: Unable to load model: 'dimdoors:unraveled_spike#inventory' referenced from: dimdoors:unraveled_spike#inventory: java.io.FileNotFoundException: dimdoors:models/item/unraveled_spike.json
 [01:34:30] [Worker-Main-13/ERROR]: Unknown model loader: forge:obj
 [01:34:30] [Worker-Main-13/ERROR]: Unknown model loader: forge:obj
 [01:34:30] [Worker-Main-13/ERROR]: Unknown model loader: forge:obj`

I'm reasonably confident this is the same issue that OP is having. I'm using 1.19.2 fabric
It is also worth noting that about 50% (Down from 75% in the previous version, so definite improvement) of the loading time on a 300+mod modpack is just this issue. (Or at least appears to be)

**Comment by BoogieMonster1O1** [comment]
In my testing, I only got 20-25 warnings compared to many more in the previous version. I'm sure I got rid of almost all of the log spam in the 1.19.2 version. The previous version didn't have the block states or model jsons for all the new blocks, so I replaced the entire assets folder with the one from 1.19.3 (which had already fixed the issue). 
This shouldn't be a huge performance issue either. The last version definitely had a lot, a lot more warnings. How are you profiling this?

**Comment by KevlarBandit** [comment]
I launched a modpack with and without dimdoors. I can rerun the test and give you actual numbers later. (Hopefully today)

**Comment by KevlarBandit** [comment]
So, 2 mins without dimdoors, 2:45 with. It is worth noting that on slower computers, that goes up dramatically. (Takes 12 minutes to load on another computer, though that was before doing some fixes on it like enabling half of its ram.)
