### ISSUE TITLE
Connection between player and their Private Pocket keeps being reset

### ISSUE THREAD

**Issue by Shadowzeny** [DimensionalDevelopment/DimDoors#64]
The best way to describe this is just to say that using a personal pocket via a quartz door doesn't always stay put. You can leave the dimension alone for a while and come back to a completely new pocket, the previous pocket still exists but the only way to get back to it is to teleport to it via text console to it.

**Comment by Runemoro** [comment]
This is already fixed in the latest dev build.

**Comment by rll18** [comment]
Can we re-open this? I have the latest version of the mod and this is still happening!

**Comment by Robijnvogel** [comment]
@rll18 refer to #85 instead and note that the issue may already be resolved in the current state of the source code. We just haven't released a new version yet.
